// <auto-generated />
namespace prj666vc.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class note_201210031 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(note_201210031));
        
        string IMigrationMetadata.Id
        {
            get { return "201310032248443_note_201210031"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
